name: TestJava
version: '3.1'
main: TestJava.testjava.TestJava
api-version: 1.18
authors: [ Edouard ]
description: TestJava
commands:
  delegation:
    description: Envoyer une lettre
    usage: /delegation <pseudo>
  rename:
    description: Renommer le village actuel
    usage: /rename <newVillageName>
  war:
    description: Déclarer la guerre
    usage: /war <villageName>
  village:
    description: Voir les infos d'un village
    usage: /village <villageName>